# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DockerInstaller@0
  displayName: Installing Docker 17
  inputs:
    dockerVersion: '17.09.0-ce'

- task: Docker@2
  displayName: Pushing on Docker Hub
  inputs:
    containerRegistry: 'bhargavd1995-dockerhub'
    repository: 'bhargavd1995/k8s-repository'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'
    addPipelineData: false
    addBaseImageData: false
